# -*- coding: utf-8 -*-
"""Porter_Stemmer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rBEagYtR08xe-BOrXciEfydYJ9Rplgvs
"""

class PorterStemmer:
    def __init__(self):
        self.b = []  # Buffer for word to be stemmed
        self.k = 0  # End-point of the word in buffer
        self.k0 = 0  # Start-point of the word in buffer
        self.j = 0  # General offset into the string

    def clean(self, word):
        # Removes non-alphabetic characters
        return ''.join([ch for ch in word if ch.isalnum()])

    def cons(self, i):
        vowels = ['a', 'e', 'i', 'o', 'u']
        if self.b[i] in vowels:
            return False
        if self.b[i] == 'y':
            return (i == self.k0) or (not self.cons(i - 1))
        return True

    def m(self):
        n = 0
        i = self.k0
        while True:
            if i > self.j:
                return n
            if not self.cons(i):
                break
            i += 1
        i += 1
        while True:
            while True:
                if i > self.j:
                    return n
                if self.cons(i):
                    break
                i += 1
            i += 1
            n += 1
            while True:
                if i > self.j:
                    return n
                if not self.cons(i):
                    break
                i += 1
            i += 1

    def vowelinstem(self):
        for i in range(self.k0, self.j + 1):
            if not self.cons(i):
                return True
        return False

    def doublec(self, j):
        if j < self.k0 + 1:
            return False
        if self.b[j] != self.b[j - 1]:
            return False
        return self.cons(j)

    def cvc(self, i):
        if i < self.k0 + 2 or not self.cons(i) or self.cons(i - 1) or not self.cons(i - 2):
            return False
        ch = self.b[i]
        return ch != 'w' and ch != 'x' and ch != 'y'

    def ends(self, s):
        length = len(s)
        if length > (self.k + 1):
            return False
        if s != ''.join(self.b[self.k - length + 1:self.k + 1]):
            return False
        self.j = self.k - length
        return True

    def setto(self, s):
        # Simplified setto method
        self.b = self.b[:self.j + 1] + list(s)
        self.k = self.j + len(s)

    def r(self, s):
        if self.m() > 0:
            self.setto(s)

    def step1ab(self):
        if self.k >= 0 and self.b[self.k] == 's':
            if self.ends("sses"):
                self.k -= 2
            elif self.ends("ies"):
                self.setto("i")
            elif self.k > 0 and self.b[self.k - 1] != 's':
                self.k -= 1
        if self.ends("eed"):
            if self.m() > 0:
                self.k -= 1
        elif (self.ends("ed") or self.ends("ing")) and self.vowelinstem():
            self.k = self.j
            if self.ends("at"):
                self.setto("ate")
            elif self.ends("bl"):
                self.setto("ble")
            elif self.ends("iz"):
                self.setto("ize")
            elif self.k >= 1 and self.doublec(self.k):
                self.k -= 1
                ch = self.b[self.k]
                if ch == 'l' or ch == 's' or ch == 'z':
                    self.k += 1
            elif self.m() == 1 and self.cvc(self.k):
                self.setto("e")

    def step1c(self):
        if self.ends("y") and self.vowelinstem():
            self.b[self.k] = 'i'

    def step2(self):
        suffix_replacements = {
            "ational": "ate",
            "tional": "tion",
            "enci": "ence",
            "anci": "ance",
            "izer": "ize",
            "abli": "able",
            "alli": "al",
            "entli": "ent",
            "eli": "e",
            "ousli": "ous",
            "ization": "ize",
            "ation": "ate",
            "ator": "ate",
            "alism": "al",
            "iveness": "ive",
            "fulness": "ful",
            "ousness": "ous",
            "aliti": "al",
            "iviti": "ive",
            "biliti": "ble",
            "isation": "ize"  # Added missing suffix from Java version
        }
        for suffix, replacement in suffix_replacements.items():
            if self.ends(suffix):
                self.r(replacement)
                break

    def step3(self):
        suffix_replacements = {
            "icate": "ic",
            "ative": "",
            "alize": "al",
            "iciti": "ic",
            "ical": "ic",
            "ful": "",
            "ness": "",
            "alise": "al"  # Added missing suffix from Java version
        }
        for suffix, replacement in suffix_replacements.items():
            if self.ends(suffix):
                self.r(replacement)
                break

    def step4(self):
        suffixes = [
            "al", "ance", "ence", "er", "ic", "able", "ible", "ant", "ement", "ment", "ent",
            "sion", "tion", "ou", "ism", "ate", "iti", "ous", "ive", "ize", "ise"  # Added missing suffix from Java version
        ]
        for suffix in suffixes:
            if self.ends(suffix) and self.m() > 1:
                self.k = self.j
                break

    def step5(self):
        if self.ends("e"):
            if self.m() > 1 or (self.m() == 1 and not self.cvc(self.k - 1)):
                self.k -= 1
        if self.ends("l") and self.doublec(self.k) and self.m() > 1:
            self.k -= 1

    def strip_prefixes(self, word):
        prefixes = ["kilo", "micro", "milli", "intra", "ultra", "mega", "nano", "pico", "pseudo"]
        for prefix in prefixes:
            if word.startswith(prefix) and len(word) > len(prefix) + 1:
                return word[len(prefix):]
        return word

    def stem(self, word):
        # Clean the word
        word = self.clean(word)
        if len(word) <= 2:
            return word  # Return the word as is if it's too short

        # Strip prefixes
        word = self.strip_prefixes(word)

        # Convert the word to a list for stemming operations
        self.b = list(word)
        self.k = len(word) - 1
        self.k0 = 0

        # Apply Porter Stemmer steps
        self.step1ab()
        self.step1c()
        self.step2()
        self.step3()
        self.step4()
        self.step5()

        return ''.join(self.b[:self.k + 1])